apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skate-license-agent.secretname" . }}
  namespace: {{ include "skate-license-agent.namespace" . }}
type: Opaque
data:
  # DB Connection details for Skate Application
  IDS_CLIENT_ID: {{ include "skate-license-agent.ids-client-id" . }}
  IDS_CLIENT_SECRET: {{ include "skate-license-agent.ids-client-secret" . }}
  ENCRYPTION_KEY: {{ include "skate-license-agent.encryption-key" . }}
  MAIL_PASS: {{ include "skate-license-agent.mail-pass" . }}
---