apiVersion: v1
kind: Service
metadata:
  name: {{ include "skate-license-agent-backend.name" . }}-service
  namespace: {{ include "skate-license-agent.namespace" . }}
  labels:
    app: {{ include "skate-license-agent-backend.name" . }}
  annotations:
    {{ include "skate-license-agent.service-annotations" . }}
spec:
  selector:
    app: {{ include "skate-license-agent-backend.name" . }}
  type: {{ include "skate-license-agent.service-type" . }}
  ports:
    - name: http
      port: {{ include "skate-license-agent.service-http-port" . }}
      targetPort: {{ include "skate-license-agent.service-target-port" . }}
      protocol: TCP
    - name: https
      port: {{ include "skate-license-agent.service-https-port" . }}
      targetPort: {{ include "skate-license-agent.service-target-port" . }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skate-license-agent-frontend.name" . }}-service
  namespace: {{ include "skate-license-agent.namespace" . }}
  labels:
    app: {{ include "skate-license-agent-frontend.name" . }}
  annotations:
    {{ include "skate-license-agent.service-annotations" . }}
spec:
  selector:
    app: {{ include "skate-license-agent-frontend.name" . }}
  type: {{ include "skate-license-agent.service-type" . }}
  ports:
    - name: http
      port: {{ include "skate-license-agent.service-http-port" . }}
      targetPort: {{ include "skate-license-agent.service-http-port" . }}
      protocol: TCP
    - name: https
      port: {{ include "skate-license-agent.service-https-port" . }}
      targetPort: {{ include "skate-license-agent.service-https-port" . }}
      protocol: TCP