{{- if and .Values.istio.enabled (.Capabilities.APIVersions.Has "security.istio.io/v1beta1") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ids-mtls
  namespace: {{ .Values.deployment.namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "PERMISSIVE" }}
{{- end }}
