### TLS secret for Skate Applications
{{- if and (.Values.ingress.secretKey) (.Values.ingress.secretCertificate) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secretName }}
  namespace: {{ .Values.deployment.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.secretCertificate }}
  tls.key: {{ .Values.ingress.secretKey }}
{{- end }}
---
### Image pull secret for pulling docker images from registry
apiVersion: v1
kind: Secret
metadata:
{{- with (first .Values.deployment.imagePullSecrets) }}
  name: {{ .name }}
{{- end }}
  namespace: {{ .Values.deployment.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "identity-server.imagePullSecrets" . }}
---
{{- $externalSecret := default "false" .Values.externalSecrets.enabled | toString | trim }}
{{- if ne $externalSecret "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: identity-server-secrets
  namespace: {{ .Values.deployment.namespace }}
type: Opaque
data:
  # DB Connection details for Skate Application
  DB_PASSWORD: {{ include "identity-server.db-password" . }}
  IDS_DB_PASSWORD: {{ include "identity-server.db-password" . }}
  SITE_KEY: {{ include "identity-server.site-key" . }}
  ID_TOKEN_ENC_SALT: {{ include "identity-server.id-token-enc-salt" . }}
  ID_TOKEN_ENC_PASSPHRASE: {{ include "identity-server.id-token-enc-passphrase" . }}
{{- end }}
---