apiVersion: v1
kind: Secret
metadata:
  name: skate-secrets
  namespace: {{ include "skate.namespace" . }}
type: Opaque
data:
  # DB Connection details for Skate Application
  DB_PASSWORD: {{ include "skate-secrets.db-password" . }}
  CRYPTO_KEY: {{ include "skate-secrets.crypto-key" . }}
  SKATE_SIGNOZ_CHANNEL_BASIC_AUTH_PASSWORD: {{ include "skate-secrets.signoz-channel-password" . | b64enc}}
  SKATE_SIGNOZ_CHANNEL_BASIC_AUTH_USERNAME: {{ include "skate-secrets.signoz-channel-user" . | b64enc}}